ItemSeeder::class,
            SupplierSeeder::class,
        ]);
=======
        $this->call([
            CategorySeeder::class,
            SupplierSeeder::class,
            ItemSeeder::class,
        ]);
